AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    # - !ruby/regexp /old_and_unused\.rb$/
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 120

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': ()
